### ISSUE TITLE
Filter company/group moods by date

### ISSUE THREAD

**Issue by jresendiz27** [Nearsoft/happinessometer-elixir#4]
- [ ] Modify `HappinessometerElixir.UserController.moods` to accept two new query params in the URL named `startDate` and `endDate` with the format YYYY-MM-DD.
- [ ] Modify Ecto query to use this two dates and just return the moods where its insertion date is between `startDate` and `endDate`
- [ ] `startDate` must be less than `endDate`, in case this is not correct endpoint must return a 400 Bad Request response with a description of the error. 
- [ ] if the user specifies `startDate` he/she must specify the `endDate` and vice-versa, in case this is not correct endpoint must return a 400 Bad Request response with a description of the error.

NOTE: look at `HappinessometerElixir.ErrorView` and use render function "error.json" with a message.

**Comment by jresendiz27** [comment]
Hi @abadongutierrez I'm trying to use the MoodView.render/2, but it requires to use a pagination and it doesn't work without it because the pattern matching. I saw that the current pagination process is being done manually, what about having a plug and reusing the pagination process for all the API operations (considering the ones with GET HTTP method) ?

I think this would be a nice improvement because will be harder to work with several paginations or copying and pasting the current implementation. 

I read about [this library](https://github.com/drewolson/scrivener), and looks promising.

**Comment by abadongutierrez** [comment]
@jresendiz27 I agree there will be repeated code with the pagination process. Implement the improvement needed to this that you believe is the best and then we can discuss at the pull request.
